"""Private operator pharmacotype registration and predictable-critic replay.

No append surface. Serve under a separate OS service identity.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import math
from pathlib import Path

from .drug_response_scoring import Store as BaseStore, canonical
from .experiment_transport import REQUEST_ID, serve
from .pharmacotype_data import prepare, digest, text
from .pharmacotype_encoder import verify, molecular, encode


def registered(manifest):
    if set(manifest) != {'protocol_id', 'hypothesis_id', 'family_id', 'cohort_id', 'cohort', 'model', 'protocol'}:
        raise ValueError('Invalid manifest')
    for key in ('protocol_id', 'hypothesis_id', 'family_id', 'cohort_id'):
        if not isinstance(manifest[key], str) or not REQUEST_ID.fullmatch(manifest[key]):
            raise ValueError('Invalid registration identifier')
    model, protocol = manifest['model'], manifest['protocol']
    verify(model)
    data = prepare(manifest['cohort'], role='confirmation')
    if data['contract_hash'] != model['contract_hash']:
        raise ValueError('Frozen assay/panel/features differ')
    # Include even excluded confirmation origins: inspected development is not fresh.
    origins = set(manifest['cohort']['aliases'].values())
    if origins & set(model['development_donors']):
        raise ValueError('Development/confirmation donor overlap')
    if protocol['schedule'] not in {'fully-frozen-v1', 'past-block-bilinear-sgd-v1'} or protocol['sampling'] != 'iid-independent-donors':
        raise ValueError('Unsupported schedule/sampling')
    for key in ('null', 'population', 'family', 'parent', 'eligibility_justification', 'normalization_justification'):
        text(protocol[key])
    if protocol['null'] != 'independence of frozen measured RNA and response representations':
        raise ValueError('Unsupported scientific null')
    if protocol['population'] != data['assay']['population'] or protocol['family'] != manifest['family_id']:
        raise ValueError('Population/family mismatch')
    if type(protocol['required_donors']) is not int or protocol['required_donors'] < 2 or protocol['required_donors'] % 2:
        raise ValueError('Prespecified even donor budget required')
    if len(data['donors']) != protocol['required_donors']:
        raise ValueError('Eligible cohort differs from frozen budget')
    # References identify operator review artifacts, not proof generated by this tool.
    for key in ('access_review', 'identity_review', 'sampling_review', 'power_review', 'privacy_review'):
        review = protocol[key]
        if not isinstance(review, str) or len(review) != 64 or any(c not in '0123456789abcdef' for c in review):
            raise ValueError('Reviewed release artifact hash required')
    if (type(protocol['null_streams']) is not int or protocol['null_streams'] < 10000
            or type(protocol['power_lower_bound']) not in (float, int)
            or not math.isfinite(protocol['power_lower_bound'])
            or not .8 <= protocol['power_lower_bound'] <= 1
            or protocol['release'] != 'operator-reviewed'):
        raise ValueError('Scientific release gate unavailable')
    if type(protocol['stake']) not in (float, int) or not math.isfinite(protocol['stake']) or not 0 <= protocol['stake'] <= .9:
        raise ValueError('Invalid stake')
    if protocol['donor_order'] != data['donors']:
        raise ValueError('Frozen canonical donor order differs')
    plate_owners = {}
    for row in manifest['cohort']['cultures']:
        donor = manifest['cohort']['aliases'][row['origin']]
        if manifest['cohort']['selected_cultures'].get(donor) != row['culture']:
            continue
        for well in row['responses']:
            if well['pool'] != 'unpooled':
                raise ValueError('Pooled assays unsupported for confirmation v1')
            key = (well['run'], well['plate'])
            if key in plate_owners and plate_owners[key] != donor:
                raise ValueError('Shared plate/control dependence unsupported for confirmation v1')
            plate_owners[key] = donor
    return data


class Store(BaseStore):
    worker_module = 'dnhacksbio.pharmacotype_scoring'

    def configure(self, path, *, ledger):
        with Path(path).open('rb') as stream:
            raw = stream.read(48*1024*1024 + 1)
        if len(raw) > 48*1024*1024:
            raise ValueError('Manifest too large')
        manifest = json.loads(raw)
        registered(manifest)
        config = canonical({'manifest': manifest, 'manifest_sha256': digest(manifest),
            'worker_sha256': self.worker_hash(), 'runtime': self.runtime(),
            'ledger': str(Path(ledger).resolve())})
        with self.connect() as con:
            con.execute('BEGIN IMMEDIATE')
            old = con.execute('SELECT config FROM settings WHERE id=1').fetchone()
            if old and old[0] != config:
                raise ValueError('Registration is frozen')
            con.execute('INSERT OR IGNORE INTO settings VALUES (1,?)', (config,))
        return self.registration()

    @staticmethod
    def worker_hash():
        from . import pharmacotype_data, pharmacotype_encoder, pharmacotype_torch, native_evidence, experiment_transport, drug_response_scoring
        return digest({Path(m.__file__).name: hashlib.sha256(Path(m.__file__).read_bytes()).hexdigest()
                       for m in (pharmacotype_data, pharmacotype_encoder, pharmacotype_torch, native_evidence, experiment_transport, drug_response_scoring)} |
                      {'pharmacotype_scoring.py': hashlib.sha256(Path(__file__).read_bytes()).hexdigest()})

    def registration(self):
        m = self.config()['manifest']
        return {'spec': {'schema': 'pharmacotype.association.v1', 'method': 'frozen_native_association',
                        **{k: m[k] for k in ('protocol_id', 'hypothesis_id', 'family_id')}},
                'input': {'cohort_id': m['cohort_id'], 'manifest_sha256': self.config()['manifest_sha256']}}

    def experiment_key(self, payload):
        m = self.config()['manifest']
        return digest({'protocol': m['protocol'], 'model': m['model'], 'cohort': m['cohort']})

    def _score_one(self, receipt):
        try:
            from .native_evidence import KERNEL, PrivateProcessStore
            config = self.config()
            if config['worker_sha256'] != self.worker_hash() or config['runtime'] != self.runtime():
                raise ValueError('Frozen software changed')
            with self.connect() as con:
                row = con.execute("SELECT payload FROM jobs WHERE receipt=? AND status='running'", (receipt,)).fetchone()
            if not row:
                return
            self.validate_payload(json.loads(row[0]))
            m = config['manifest']; data = registered(m); model = m['model']; p = m['protocol']
            x, y = molecular(data['x'], model), encode(data['y'], model['response'])
            spec = dict(kernel=KERNEL, null=p['null'], population=p['population'], panel=digest(data['panel']),
                model_hashes=[digest(model['molecular']), digest(model['response'])], qc_hash=data['contract_hash'],
                data_hash=data['source_hash'], crosswalk_hash=digest(m['cohort']['aliases']),
                acquisition_hash=p['access_review'], family=p['family'], parent=p['parent'], sampling=p['sampling'],
                exclusions=model['development_donors'], weights=model['critic'], stake=p['stake'],
                eligible_donors=data['donors'], reuse_policy='globally-disjoint-canonical-donors-v1', schedule=p['schedule'])
            ledger = PrivateProcessStore(config['ledger'])
            # Process alias includes queue identity to avoid administrative collisions across queues.
            alias = 'pharm-' + self.experiment_key(json.loads(row[0]))
            ledger.register(alias, spec)
            for i in range(0, len(data['donors']), 2):
                ledger.advance(alias, i//2, data['donors'][i:i+2], x[i:i+2], y[i:i+2])
            result = ledger.export(alias)
            result.update(status='scored', method='pharmacotype.association.v1',
                          exclusions=data['exclusions'], manifest_sha256=config['manifest_sha256'])
            with self.connect() as con:
                con.execute("UPDATE jobs SET status='completed',result=? WHERE receipt=? AND status='running'", (canonical(result), receipt))
        except Exception as exc:
            with self.connect() as con:
                con.execute("UPDATE jobs SET status='failed',error=? WHERE receipt=? AND status='running'", (type(exc).__name__, receipt))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    for name in ('register', 'serve', 'replay', 'score-one', 'export'):
        p = sub.add_parser(name); p.add_argument('--state', required=True)
        if name == 'register':
            p.add_argument('--manifest', required=True); p.add_argument('--ledger', required=True); p.add_argument('--output', required=True)
        if name == 'serve':
            p.add_argument('--host', default='127.0.0.1'); p.add_argument('--port', type=int, default=8797)
        if name == 'score-one': p.add_argument('--receipt', required=True)
        if name == 'export': p.add_argument('--output', required=True)
    args = parser.parse_args(argv); store = Store(args.state)
    if args.command == 'register':
        result = store.configure(args.manifest, ledger=args.ledger)
        with open(args.output, 'x', opener=lambda p,f: os.open(p,f,0o600)) as stream:
            json.dump(result, stream, indent=2)
    elif args.command == 'serve': serve(store, args.host, args.port)
    elif args.command == 'score-one': store.score_one(args.receipt)
    elif args.command == 'replay':
        # Same worker ownership/recovery protocol as the transport service.
        import fcntl
        with (store.directory/'worker.lock').open('a') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            with store.connect() as con:
                con.execute("UPDATE jobs SET status='queued',error=NULL WHERE status IN ('running','failed')")
            while store.process_one(): pass
    else: store.export(args.output)


if __name__ == '__main__': main()
