import { Component, useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, Aperture, Download, Focus, RotateCcw } from 'lucide-react';
import type { JsonRecord } from '@/lib/types';
import { validateGeometry, type Geometry, type Recipe, type Vec3 } from '@/lib/inhibitor';
import InhibitorScene from './InhibitorScene';
import '../inhibitor.css';

type Review = {ready:()=>Promise<number>; setCamera:(shot:Recipe['shot'])=>void;setStyle:(style:Recipe['style'])=>void;setFrame:(frame:number)=>void;select:(ids:string[])=>void;loadFixture:(hash:string)=>void;capture:(revision:number)=>Promise<{png:string;recipe:Recipe}>};
declare global {interface Window {sceneReview?:Review}}
class SceneBoundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true}};render(){return this.state.error?<p role="alert">The 3D renderer is unavailable. Return to the experiment for the reference viewer and coordinates.</p>:this.props.children}}
function save(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function InhibitorWorkbench({artifact,url,owner,onClose}:{artifact:JsonRecord;url:string;owner:string;onClose:()=>void}){
 const [g,setG]=useState<Geometry|null>(null),[error,setError]=useState('');
 const [recipe,setRecipe]=useState<Recipe|null>(null),[query,setQuery]=useState(''),[tab,setTab]=useState('contacts');
 const [contacts,setContacts]=useState<JsonRecord|null>(null),[measurement,setMeasurement]=useState<JsonRecord|null>(null),[preparation,setPreparation]=useState<JsonRecord|null>(null);
 const latest=useRef<Recipe|null>(null);latest.current=recipe;const rendered=useRef(-1),canvas=useRef<HTMLCanvasElement|null>(null);
 const api=useCallback(async(params:Record<string,string|string[]>={})=>{const target=new URL(url,location.origin);Object.entries(params).forEach(([k,v])=>(Array.isArray(v)?v:[v]).forEach(x=>target.searchParams.append(k,x)));const r=await fetch(target);const data=await r.json();if(!r.ok)throw Error(data.error||'Experiment geometry unavailable');return data;},[url]);
 useEffect(()=>{let active=true;api().then(data=>{if(!active)return;const geometry=validateGeometry(data,artifact.sha256);setG(geometry);const ligand=geometry.residues.filter(r=>r.kind==='ligand').sort((a,b)=>b.atoms.length-a.atoms.length)[0];setRecipe({schema_version:1,source_hash:geometry.source_hash,revision:0,style:'matte',shot:'pocket',ligand:ligand?.id||'',model:ligand?.model||0,clip:false,selected:[],frame:0});}).catch(e=>active&&setError(e.message));return()=>{active=false};},[api,artifact.sha256]);
 const patch=useCallback((p:Partial<Recipe>)=>{rendered.current=-1;setRecipe(r=>r?{...r,...p,revision:r.revision+1}:r)},[]);
 const ack=useCallback((revision:number,el:HTMLCanvasElement)=>{if(latest.current?.revision===revision){rendered.current=revision;canvas.current=el;}},[]);
 const onCamera=useCallback((position:Vec3,target:Vec3)=>patch({camera:{position,target}}),[patch]);
 const select=useCallback((id:string)=>{if(!g?.atoms.some(a=>a.id===id))throw Error('Unknown atom identity');setMeasurement(null);setRecipe(r=>r?{...r,selected:r.selected.includes(id)?r.selected.filter(x=>x!==id):[...r.selected.slice(-1),id],revision:r.revision+1}:r);},[g]);
 useEffect(()=>{if(!recipe?.ligand)return;let live=true;setContacts(null);api({operation:'contacts',residue:recipe.ligand}).then(v=>live&&setContacts(v)).catch(e=>live&&setError(e.message));return()=>{live=false};},[api,recipe?.ligand]);
 useEffect(()=>{let live=true;api({operation:'preparation'}).then(v=>live&&setPreparation(v)).catch(e=>live&&setError(e.message));return()=>{live=false};},[api]);
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key)}},[onClose]);
 const ready=useCallback(async()=>{const expected=latest.current?.revision;await document.fonts.ready;const start=performance.now();while(rendered.current!==expected || !canvas.current){if(latest.current?.revision!==expected)throw Error('Scene revision changed while waiting');if(performance.now()-start>15000)throw Error('Scene did not finish rendering');await new Promise(requestAnimationFrame);}return expected!;},[]);
 const capture=useCallback(async(expected:number)=>{if(expected!==latest.current?.revision)throw Error('Stale capture revision');await ready();if(expected!==latest.current?.revision)throw Error('Stale capture revision');return {png:canvas.current!.toDataURL('image/png'),recipe:structuredClone(latest.current!)};},[ready]);
 useEffect(()=>{if(new URLSearchParams(location.search).get('sceneReview')!=='1' || !g)return;
 const controller:Review={ready,setCamera:shot=>patch({shot,camera:undefined}),setStyle:style=>{if(!['matte','luminous'].includes(style))throw Error('Unknown style');patch({style})},setFrame:frame=>{if(frame!==0)throw Error('No recorded trajectory available')},select:ids=>{if(ids.length>2||ids.some(id=>!g.atoms.some(a=>a.id===id)))throw Error('Unknown selection');patch({selected:ids})},loadFixture:hash=>{if(hash!==g.source_hash)throw Error('Fixture hash mismatch');patch({shot:'arrival',camera:undefined,selected:[]})},capture};window.sceneReview=controller;return()=>{if(window.sceneReview===controller)delete window.sceneReview};},[g,ready,patch,capture]);
 const measure=async()=>{if(!recipe)return;try{setMeasurement(await api({operation:'measure',atom:recipe.selected}));setError('')}catch(e){setError((e as Error).message)}};
 const exportPlate=async()=>{try{const result=await capture(recipe!.revision);const a=document.createElement('a');a.href=result.png;a.download='inhibitor-evidence-plate.png';a.click();save('inhibitor-report.json',JSON.stringify({schema_version:1,owner,provenance:artifact.provenance,scene:result.recipe,contacts,measurement,preparation,warnings:g?.warnings,interpretation:'Exploratory deposited geometry. Affinity and cellular inhibition not measured.',follow_up:'Freeze a justified preparation protocol and validate known-ligand recovery before docking.'},null,2),'application/json');}catch(e){setError((e as Error).message)}};
 const ligand=g?.residues.find(r=>r.id===recipe?.ligand);
 return createPortal(<div className="pocket-workbench" role="dialog" aria-modal="true" aria-label="Inhibitor workbench">
  <header className="pocket-header"><button autoFocus onClick={onClose}><ArrowLeft size={16}/> Return to experiment</button><span className="pocket-owner">{owner}</span><span className="pocket-reference">{String(artifact.provenance.category).replaceAll('_',' ')}</span></header>
  <div className="pocket-title"><div><p className="pocket-eyebrow">MOLECULAR INSTRUMENTS / 01</p><h1>The pocket observatory<span>.</span></h1><p>Inspect the geometry behind the hypothesis.</p></div><button onClick={()=>void exportPlate()} disabled={!recipe}><Download size={16}/> Evidence plate</button></div>
  {error&&<div role="alert" className="pocket-error">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
  <div className="pocket-layout"><main className="pocket-stage">
   <div className="pocket-stage-meta"><span>{artifact.name}</span><span>{recipe?.shot==='arrival'?'Deposited structure':'Pocket detail'} · Å</span></div>
   {g&&recipe?<SceneBoundary><InhibitorScene g={g} recipe={recipe} pick={select} ack={ack} onCamera={onCamera}/></SceneBoundary>:<p className="pocket-loading">{error?'Geometry unavailable':'Reading canonical coordinates…'}</p>}
   <div className="pocket-scene-caption"><span className="pocket-amber-dot"/><strong>{ligand?`${ligand.name} · ${ligand.chain} ${ligand.sequence}`:'No deposited ligand'}</strong><span>{ligand?'Reference pose · affinity not measured':'Select a residue to inspect its surroundings'}</span></div>
   <div className="pocket-camera-tools"><button title="Full structure" onClick={()=>patch({shot:'arrival',camera:undefined})}><RotateCcw size={17}/> Arrival</button><button onClick={()=>patch({shot:'pocket',camera:undefined})}><Focus size={17}/> Pocket</button><button onClick={()=>patch({shot:'oblique',camera:undefined})}><Aperture size={17}/> Oblique</button></div>
  </main><aside className="pocket-inspector">
   <p className="pocket-eyebrow">EXPERIMENT LENS</p><h2>{ligand?.name||'Structure inspection'}</h2><p className="pocket-secondary">{ligand?`${ligand.atoms.length} deposited atoms · chain ${ligand.chain}`:'No candidate poses collected'}</p>
   <label>Reference residue<select aria-label="Reference residue" value={recipe?.ligand||''} onChange={e=>{const r=g?.residues.find(r=>r.id===e.target.value);patch({ligand:e.target.value,model:r?.model||0,selected:[],camera:undefined})}}><option value="">Choose a residue</option>{g?.residues.filter(r=>r.kind==='ligand').map(r=><option key={r.id} value={r.id}>{r.name} · {r.chain} {r.sequence} · model {r.model+1}</option>)}</select></label>
   <div className="pocket-tabs" role="tablist" aria-label="Pocket inspector">{['contacts','preparation','display'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
   {tab==='contacts'&&<><div className="pocket-stat"><strong>{contacts?.contacts.length??'—'}</strong><span>heavy-atom proximities<br/>within 4.0 Å</span></div><p className="pocket-secondary">Proximity alone does not assign a hydrogen bond.</p><div className="pocket-contact-list">{contacts?.contacts.slice(0,40).map((c:JsonRecord,i:number)=>{const a=g?.atoms.find(a=>a.id===c.atom_ids[1]);const r=g?.residues.find(r=>r.id===a?.residue_id);return <button key={i} onClick={()=>{patch({selected:c.atom_ids});setMeasurement({value:c.distance,units:'Å',coordinate_frame:'canonical',atom_ids:c.atom_ids})}}><span>{r?.name} {r?.sequence} <small>{a?.name}</small></span><strong>{c.distance.toFixed(2)} Å</strong></button>})}</div>{contacts?.contacts.length===0&&<p>No contacts within the declared cutoff.</p>}</>}
   {tab==='preparation'&&<div className="pocket-audit"><h3>Deposited → unchanged</h3><p>{preparation?.reason||'Reading preparation status…'}</p><dl><dt>Retained waters</dt><dd>{preparation?.retained.waters??'—'}</dd><dt>Alternate atoms</dt><dd>{preparation?.retained.alternate_atoms??'—'}</dd><dt>Hydrogens present</dt><dd>{preparation?.retained.hydrogens??'—'}</dd></dl><strong>Docking unavailable</strong><p>No prepared receptor or seeded docking results have been collected.</p><strong>Dynamics unavailable</strong><p>No parameterized system or recorded trajectory.</p></div>}
   {tab==='display'&&<div className="pocket-audit"><label>Treatment<select aria-label="Render treatment" value={recipe?.style} onChange={e=>patch({style:e.target.value as Recipe['style']})}><option value="matte">Sculpted matte</option><option value="luminous">Luminous pocket</option></select></label><label className="pocket-check"><input type="checkbox" checked={recipe?.clip||false} onChange={e=>patch({clip:e.target.checked})}/> Cutaway · display only</label><p>CA traces, atom radii and translucent atom envelopes are illustrative. The cutaway hides display geometry; measurements use original coordinates.</p><p>{g?.coordinate_frame}</p><button onClick={()=>save('scene.json',JSON.stringify(recipe,null,2),'application/json')}>Save camera bookmark</button></div>}
   <div className="pocket-measure"><label>Find an atom or residue<input aria-label="Find an atom or residue" placeholder="e.g. GLY, 604, N1" value={query} onChange={e=>setQuery(e.target.value)}/></label>{query&&<div className="pocket-search-results">{g?.atoms.filter(a=>a.model===recipe?.model&&`${a.id} ${a.name}`.toLowerCase().includes(query.toLowerCase())).slice(0,12).map(a=><button key={a.id} onClick={()=>select(a.id)}>{a.id.split('/').slice(2).join('/')}</button>)}</div>}<p>{recipe?.selected.length||0} / 2 atoms selected</p><button disabled={recipe?.selected.length!==2} onClick={()=>void measure()}>Measure canonical distance</button>{measurement&&<output><strong>{measurement.value.toFixed(3)} {measurement.units}</strong><span>Canonical coordinates</span><details><summary>Atom identities</summary>{measurement.atom_ids.map((id:string)=><code key={id}>{id}</code>)}</details></output>}</div>
  </aside></div>
  <footer className="pocket-footer"><span>Drag to orbit · scroll to zoom · right-drag to pan · select atoms to measure</span><span>{g?.atoms.length.toLocaleString()} atoms · {g?.producer}</span><details><summary>Source & limitations</summary><p>{JSON.stringify(artifact.provenance)}</p><p>SHA-256 {g?.source_hash}</p>{g?.warnings.map(w=><p key={w}>{w}</p>)}</details></footer>
 </div>,document.body);
}
