#!/usr/bin/env python
"""Render `docs/CAPABILITIES.md` FROM the live code.

Everything here is read out of live Python objects at build time, so the index can only go stale if the
generator stops being run, which `tests/test_capability_index.py` prevents by regenerating and diffing.
What belongs here: enumerable, closed vocabularies a reader of the system needs to know exist. Rationale
and trade-offs are hand-written prose elsewhere.

  uv run python scripts/gen_capability_index.py            # write docs/CAPABILITIES.md
  uv run python scripts/gen_capability_index.py --check    # exit 1 if the file is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

OUT = Path("docs/CAPABILITIES.md")


def _table(rows: list[tuple], head: tuple[str, ...]) -> list[str]:
    out = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def render() -> str:
    L: list[str] = []
    L += ["<!-- GENERATED BY scripts/gen_capability_index.py — Do not edit by hand. -->",
          "<!-- Run `uv run python scripts/gen_capability_index.py` after changing a closed vocabulary. -->",
          "", "# Capability index — what the engine can represent",
          "",
          "Rendered from live code, so it is true by construction. If this disagrees with a prose doc,",
          "**this is right.**", ""]
    L += _claim_layer()
    L += _rigor_layer()
    L += _explorer_layer()
    L += _store_layer()
    return "\n".join(L) + "\n"


def _claim_layer() -> list[str]:
    """The predicate vocabulary a literature claim may carry."""
    from dnhacksbio.litmap import vocab as V

    L = ["## Predicates", "",
         f"{len(V.PREDICATES)} canonical predicates. The sign is the default polarity: +1 enabling,",
         "-1 repressive, 0 undirected. A predicate outside this table is refused, never coerced.", ""]
    L += _table([(f"`{p}`", f"{s:+d}" if s else "0") for p, (_, s) in sorted(V.PREDICATES.items())],
                ("predicate", "sign"))
    assoc = {p for p, (_, s) in V.PREDICATES.items() if s == 0}
    L += ["", "**Associative predicates** (sign 0, never novelty-disqualifying on their own): "
          + ", ".join(f"`{p}`" for p in sorted(assoc)), ""]
    L += ["", f"**Synonyms** (`CANONICAL_PREDICATES`, {len(V.CANONICAL_PREDICATES)} surface forms "
          "folded onto a canonical predicate): "
          + ", ".join(f"`{k}`→`{v}`" for k, v in sorted(V.CANONICAL_PREDICATES.items())), ""]
    return L


def _rigor_layer() -> list[str]:
    """The falsifier's verdicts and thresholds: the numbers that decide whether a result survives."""
    from dnhacksbio import falsifier as F
    from dnhacksbio import methods as M

    L = ["## Falsifier verdicts and thresholds", "",
         "The soundness gate. A verdict names why something was killed: 'the data contradicted it' and",
         "'the test could not decide' are different outcomes.", ""]
    L += _table([(f"`{k}`", f"`{v}`") for k, v in sorted(F.KILL_KIND.items())],
                ("kill reason", "verdict"))
    L += ["", "**Verdicts** (`KILL_KINDS`): " + ", ".join(f"`{k}`" for k in sorted(F.KILL_KINDS))
          + f"; unknown kills fall back to `{F.UNKNOWN_KILL}`.", ""]
    nums = {n: getattr(F, n) for n in dir(F)
            if n.isupper() and isinstance(getattr(F, n), (int, float)) and not isinstance(getattr(F, n), bool)}
    L += ["**Thresholds** — change one and every downstream verdict moves:", ""]
    L += _table([(f"`{k}`", v) for k, v in sorted(nums.items())], ("constant", "value"))
    L += ["", f"**Trust classes** (`methods.TRUST_CLASSES`): "
          + ", ".join(f"`{c}`" for c in sorted(M.TRUST_CLASSES))
          + " — a statistic is only `audited-statistic` if it came through the `ToolResult` contract.", ""]
    return L


def _explorer_layer() -> list[str]:
    """The reasoning agent's own closed vocabularies."""
    from dnhacksbio.explorer import exploration as X

    return ["## Explorer notebook vocabulary", "",
            "The agent's exploration log — what a node can BE and where it can get to.", "",
            f"**Kinds** (`KINDS`): " + ", ".join(f"`{k}`" for k in X.KINDS), "",
            f"**Statuses** (`STATUSES`): " + ", ".join(f"`{s}`" for s in X.STATUSES), ""]


def _store_layer() -> list[str]:
    """The knowledge-graph tables, introspected from a freshly created database."""
    from dnhacksbio.litmap.store import KGStore

    L = ["## Knowledge-graph store tables", "",
         "Introspected from a freshly created database, so this is the schema the code actually builds.", ""]
    s = KGStore(":memory:")
    try:
        con = s.con
        names = [r[0] for r in con.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema='main' "
            "ORDER BY table_name").fetchall()]
        for t in names:
            cols = con.execute(
                "SELECT column_name, data_type FROM information_schema.columns "
                "WHERE table_name=? ORDER BY ordinal_position", [t]).fetchall()
            L += [f"**`{t}`** ({len(cols)} columns): "
                  + ", ".join(f"`{c}` {d.lower()}" for c, d in cols), ""]
    finally:
        try:
            s.close()
        except Exception:
            pass
    return L


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed file is stale")
    a = ap.parse_args()
    new = render()
    if a.check:
        old = OUT.read_text() if OUT.exists() else ""
        if old != new:
            print(f"STALE: {OUT} does not match the code. Run: "
                  f"uv run python scripts/gen_capability_index.py")
            sys.exit(1)
        print(f"{OUT} is current.")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(new)
        print(f"wrote {OUT} ({len(new.splitlines())} lines)")
